### ISSUE TITLE
Pendente alias da capital

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/BR_new#10]
Capital do pais (fica no nivel 2), https://afa.codes/BR-DF-Brasilia~FRRS  existe mas https://afa.codes/BR-DF~FRRS não funciona

Capital do estado (permite nivel 3 repetindo o nivel 2 com suas 2 letras), https://afa.codes/BR-SP-SaoPaulo~FRRS existe, mas https://afa.codes/BR-SP-SP~FRRS

**Comment by 0e1** [comment]
Fiz correções.

Documentado no rascunho: https://wiki.addressforall.org/doc/osmc:Api


Issue relacionada: https://github.com/osm-codes/gridMap-draftPages/issues/69
