### ISSUE TITLE
Codificação do CEP é definitiva, vale o hifemTrazer 

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/BR_new#11]
Separar issues e entre WS e BR_new as issues, ver https://github.com/osm-codes/gridMap-draftPages/issues/82
e https://github.com/osm-codes/WS/issues/50

Definir regrexes em CSV ou JSON. As regexes podem ser de dois tipos: genérica-global (no WS), e específica por sobrescrita (no país).  

**Cada país precisa do eu próprio gerador de NGINX** a partir de CSV ou JSON (local!) que alimentará Mustaches.

**Comment by 0e1** [comment]
Consolidei essa issue em https://github.com/osm-codes/WS/issues/50#issue-1951837674.
