### ISSUE TITLE
Bug na segmentação das células FR e FQ da base16h 

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/BR_new#3]
Não poderiam perder o prefixo `F`, 

![image](https://user-images.githubusercontent.com/1651447/195403816-924375b5-0714-4180-9b50-55127f210dfc.png)

----

Repare que em dois dígitos aparecem corretamente, 

![image](https://user-images.githubusercontent.com/1651447/195403533-f6c5d6ca-4ae9-4c65-a145-afa59eb02503.png)

**Comment by 0e1** [comment]
Resolvida a situação em https://github.com/osm-codes/CO_new/commit/006a506ab35e42d5cf605ed62039df67205ea684

![screen](https://user-images.githubusercontent.com/41844788/196526373-40f15a94-6ffe-452a-b4d9-08d5320a32db.png)
