### ISSUE TITLE
Coberturas em overlap

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/BR_new#4]
A eficiência de coberura em manchas urbanas demanda o uso da opção de definição baseada em overlap. Isso se confirma no algoritmo Mapcode.

Exemplo de São Paulo, que na sua "cobertura natural" requer apenas 5 celulas de 32 km (FYS,FYU,FYV,FZJ,FZK). A cobertura da área mais antiga e densamente povoada pode ser realizada por overlap:

![image](https://user-images.githubusercontent.com/1651447/196026997-87398036-fde8-4476-b1bd-bcfda6a1a570.png)

O resultado é 26+5 = 31, sobrando 1 de reserva.

**Comment by 0e1** [comment]
O https://github.com/osm-codes/GGeohash/commit/350b5b12ed346b1db101a8cd363a782851fc661c ordena a tabela de coberturas de maneira que prefixos maiores tem preferencia. Acredito ser o suficiente para o _overlap_.

Exemplo em http://osm.codes/BR-RJ-RioJaneiro:

![screen](https://user-images.githubusercontent.com/41844788/196817938-7e529b95-1674-4737-9643-a62cea5cc17d.png)


Continuar a discussão em https://github.com/osm-codes/GGeohash/issues/5.
