### ISSUE TITLE
Incluir arquivo CSV dos aliases

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/BR_new#9]
Siglas e demais sinônimos do prefixo canônico devem ser publicados.

**Comment by 0e1** [comment]
Publiquei da seguinte maneira para avaliar:

- **synonym.csv**: sinônimos oriundos da tabela optim.jurisdiction_abbrev_option
- **synonym_ref.csv**: referencia para abbrevref

Ver arquivos em:

https://github.com/osm-codes/BR_new/tree/main/data/synonym.csv 
https://github.com/osm-codes/BR_new/tree/main/data/synonym_ref.csv

https://github.com/osm-codes/CO_new/tree/main/data/synonym.csv 
https://github.com/osm-codes/CO_new/tree/main/data/synonym_ref.csv

https://github.com/osm-codes/UY_new/tree/main/data/synonym.csv 
https://github.com/osm-codes/UY_new/tree/main/data/synonym_ref.csv

**Comment by 0e1** [comment]
Consolidei esse assunto na issue mais antiga sobre o tema: https://github.com/osm-codes/WS/issues/31
